### ДЗ №5. Разложить матрицу в SVD.

In [1]:
import numpy as np
from scipy import linalg

In [7]:
a = np.array([[3, 7], 
              [5, 2]])

In [8]:
u, s, vh = linalg.svd(a, full_matrices=True)
u, s, vh

(array([[-0.85065081, -0.52573111],
        [-0.52573111,  0.85065081]]),
 array([8.71337969, 3.32821489]),
 array([[-0.59455781, -0.80405286],
        [ 0.80405286, -0.59455781]]))

In [9]:
u.shape, s.shape, vh.shape

((2, 2), (2,), (2, 2))

In [13]:
a_lossless = np.dot(u[:, :6] * s, vh)
a_lossless

array([[3., 7.],
       [5., 2.]])

In [10]:
np.allclose(a, np.dot(u[:, :6] * s, vh))

True

Возьмем только одно сингулярное число из двух: `s[0, 0]`. 

И восстановим матрицу `a` из двух векторов `u[:, 0]`, `vh[0, :]` и одного элемента `s[0,0]`.

In [15]:
us_restored = np.expand_dims(np.expand_dims(u[:, 0], axis=1)  @ np.expand_dims(s[0], axis=0), axis=1)
us_restored, us_restored.shape

(array([[-7.41204348],
        [-4.5808948 ]]), (2, 1))

In [17]:
vh_restored = np.expand_dims(vh[0, :], axis=0)
vh_restored, vh_restored.shape

(array([[-0.59455781, -0.80405286]]), (1, 2))

In [18]:
a_restored = us_restored @ vh_restored
a_restored, a_restored.shape

(array([[4.40688837, 5.95967478],
        [2.7236068 , 3.68328157]]), (2, 2))

In [41]:
np.allclose(a, a_restored)

# Восстановление произошло с потерями, поскольку отбросив элемент a[1, 1], 
# мы получили долю необъяснённой дисперсии:
# http://www.machinelearning.ru/wiki/index.php?title=Метод_главных_компонент#.D0.9E.D1.81.D1.82.D0.B0.D1.82.D0.BE.D1.87.D0.BD.D0.B0.D1.8F_.D0.B4.D0.B8.D1.81.D0.BF.D0.B5.D1.80.D1.81.D0.B8.D1.8F
a[1, 1]/(a[0, 0] + a[1, 1])

0.4

In [42]:
# Норма Фробениуса для исходной и восстановленной матриц
np.linalg.norm(a_lossless, ord='fro'), np.linalg.norm(a_restored, ord='fro')

(9.327379053088817, 8.713379692963404)